-- MySQL Script generated by MySQL Workbench
-- Thu Jan  1 23:07:23 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nyxara
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nyxara
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nyxara` DEFAULT CHARACTER SET utf8 ;
USE `nyxara` ;

-- -----------------------------------------------------
-- Table `nyxara`.`tb_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nyxara`.`tb_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nyxara`.`tb_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nyxara`.`tb_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dtCreated` DATETIME DEFAULT NOW(),
  PRIMARY KEY (`id`, `name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nyxara`.`tb_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nyxara`.`tb_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUserDiscord` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(110) NOT NULL,
  `password` VARCHAR(225) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `dtCreated` DATETIME DEFAULT NOW(),
  `dtUpdated` DATETIME NULL,
  `idPermission` INT NOT NULL,
  `tb_status_id` INT NOT NULL,
  `tb_status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUserDiscord_UNIQUE` (`idUserDiscord` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_tb_users_tb_permission_idx` (`idPermission` ASC) VISIBLE,
  INDEX `fk_tb_users_tb_status1_idx` (`tb_status_id` ASC, `tb_status_name` ASC) VISIBLE,
  CONSTRAINT `fk_tb_users_tb_permission`
    FOREIGN KEY (`idPermission`)
    REFERENCES `nyxara`.`tb_permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_users_tb_status1`
    FOREIGN KEY (`tb_status_id` , `tb_status_name`)
    REFERENCES `nyxara`.`tb_status` (`id` , `name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nyxara`.`tb_playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nyxara`.`tb_playlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(110) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `platform` VARCHAR(45) NOT NULL,
  `dtCreated` DATETIME DEFAULT NOW(),
  `dtUpdated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nyxara`.`tb_music_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nyxara`.`tb_music_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(110) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `platform` VARCHAR(45) NOT NULL,
  `dtCreated` DATETIME DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nyxara`.`tb_discord_servers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nyxara`.`tb_discord_servers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `idServerDiscord` VARCHAR(45) NOT NULL,
  `dtCreated` DATETIME DEFAULT NOW(),
  `dtUpdated` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idServerDiscord_UNIQUE` (`idServerDiscord` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nyxara`.`tb_bot_configuretion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nyxara`.`tb_bot_configuretion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idMessageChannel` VARCHAR(45) NULL,
  `idVoiceChannel` VARCHAR(45) NULL,
  `dtCreated` DATETIME DEFAULT NOW(),
  `dtUpdated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nyxara`.`tb_users_playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nyxara`.`tb_users_playlist` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `idPlaylist` INT NOT NULL,
  INDEX `fk_tb_user_playlist_tb_users1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_tb_user_playlist_tb_playlist1_idx` (`idPlaylist` ASC) VISIBLE,
  CONSTRAINT `fk_tb_user_playlist_tb_users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `nyxara`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_user_playlist_tb_playlist1`
    FOREIGN KEY (`idPlaylist`)
    REFERENCES `nyxara`.`tb_playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nyxara`.`tb_users_discord_server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nyxara`.`tb_users_discord_server` (
  `idUser` INT NOT NULL,
  `idMusicHistory` INT NOT NULL,
  INDEX `fk_tb_users_music_history_tb_users1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_tb_users_music_history_tb_music_history1_idx` (`idMusicHistory` ASC) VISIBLE,
  CONSTRAINT `fk_tb_users_music_history_tb_users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `nyxara`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_users_music_history_tb_music_history1`
    FOREIGN KEY (`idMusicHistory`)
    REFERENCES `nyxara`.`tb_music_history` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nyxara`.`tb_users_dsicord_servers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nyxara`.`tb_users_dsicord_servers` (
  `idUser` INT NOT NULL,
  `idDiscordServer` INT NOT NULL,
  INDEX `fk_table1_tb_users1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_table1_tb_discord_server1_idx` (`idDiscordServer` ASC) VISIBLE,
  CONSTRAINT `fk_table1_tb_users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `nyxara`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_tb_discord_server1`
    FOREIGN KEY (`idDiscordServer`)
    REFERENCES `nyxara`.`tb_discord_servers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nyxara`.`tb_discord_servers_bot_configuretion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nyxara`.`tb_discord_servers_bot_configuretion` (
  `idDiscordServer` INT NOT NULL,
  `IdBotConfiguretion` INT NOT NULL,
  INDEX `fk_tb_discord_servers_bot_configuretion_tb_discord_servers1_idx` (`idDiscordServer` ASC) VISIBLE,
  INDEX `fk_tb_discord_servers_bot_configuretion_tb_bot_configuretio_idx` (`IdBotConfiguretion` ASC) VISIBLE,
  CONSTRAINT `fk_tb_discord_servers_bot_configuretion_tb_discord_servers1`
    FOREIGN KEY (`idDiscordServer`)
    REFERENCES `nyxara`.`tb_discord_servers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_discord_servers_bot_configuretion_tb_bot_configuretion1`
    FOREIGN KEY (`IdBotConfiguretion`)
    REFERENCES `nyxara`.`tb_bot_configuretion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
