version: "3.3"
services:
  database:
    image: mysql:5.2
    container_name: mysql-botdiscord
    restart: always
    environment:
      MYSQL_DATABASE: "dart"
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./volumes/mysql:/var/lib/mysql"
      - "./database.sql:/docker-entrypoint-initdb.d/database.sql"
